# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-16 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='photo',
            name='style',
            field=models.CharField(choices=[('ML', 'Mona Lisa'), ('TSN', 'The Starry Night'), ('TS', 'The Scream'), ('GPE', 'Girl with a Pearl Earring')], default='ML', max_length=5),
            preserve_default=False,
        ),
    ]
