# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 22:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0002_photo_style'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='photo',
            options={'ordering': ['-id']},
        ),
        migrations.AddField(
            model_name='photo',
            name='is_highlighted',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='photo',
            name='style',
            field=models.CharField(choices=[('ML', 'Mona Lisa'), ('TSN', 'Starry Night'), ('TS', 'Scream'), ('GPE', 'Girl with a Pearl Earring')], max_length=5),
        ),
        migrations.AlterField(
            model_name='photo',
            name='title',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
