# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 23:03
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0003_auto_20161106_2246'),
    ]

    operations = [
        migrations.CreateModel(
            name='Style',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='styles/%Y/%m/%d/')),
                ('title', models.CharField(max_length=100)),
            ],
        ),
        migrations.AlterField(
            model_name='photo',
            name='style',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='photos.Style'),
        ),
    ]
