# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-06 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('photos', '0004_auto_20161106_2303'),
    ]

    operations = [
        migrations.AlterField(
            model_name='photo',
            name='style',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='photos.Style'),
        ),
    ]
